# Generated by Django 5.0.14 on 2026-10-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=120, verbose_name='Nombre del Cliente')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección de Entrega')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de Contacto')),
                ('descripcion_productos', models.TextField(verbose_name='Detalle de Productos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Total a Pagar ($)')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparación', 'En preparación'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
